// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Package transport implements high-performance abstractions for sharing data between goroutines.
package transport

import (
	"gonum.org/v1/gonum/num/quat"
	"gonum.org/v1/gonum/spatial/r3"
)

type TimedFloat64 struct {
	value   float64
	timings EventTimings
}

// Package transport implements high-performance abstractions for sharing data between goroutines.

type TimedR3Vec struct {
	value   r3.Vec
	timings EventTimings
}

// Package transport implements high-performance abstractions for sharing data between goroutines.

type TimedQuatNumber struct {
	value   quat.Number
	timings EventTimings
}
